### PR TITLE
Moving to os brep gmsh workflow

### PR DESCRIPTION
**Pull request by shimwell**
This PR is an attempt to get the CAD simulations working using the emerging open source workflow

### CODE REVIEW

**Comment by shimwell** [comment]
task 11 is failing with ```AttributeError: 'Reactor' object has no attribute 'export_dagmc_h5m'``` on CircleCI. This is due to the use of an older version of the Paramak on the Dockerimage

**Comment by shimwell** [comment]
I shall have another go at this once we have updated the paramak to work with cq 2.2 / cq master
